create table direccion (
id_direccion nchar(7) not null CONSTRAINT pk_ID_DIRECCION primary key ,
distrito nvarchar2(50),
direccion VARCHAR2(50)
);

CREATE TABLE PERSONA (
-- PRIMARY KEY DOC--
DOC CHAR(10),
NOMBRE VARCHAR(25) NOT NULL,
APELLIDO VARCHAR(25) NOT NULL,
FECHA_NACIMIENTO DATE NOT NULL,
-- SOLO ACEPTA M O F 
SEXO CHAR(1) CONSTRAINT CH_SEXO CHECK(SEXO IN ('M', 'F')),
--LA LLAVE PRIMARIA ES DOC
CONSTRAINT PK_DOC PRIMARY KEY (DOC)
);

create table telefono(
id_telefono number(2) not null constraint pk_id_telefono primary key,
telefono number(10)
);

create table email(
idemail nchar(7),
DNI char(10),
email nvarchar2(30) not null,
descripcion nvarchar2(30) not null,
constraint pk_codigo
    primary key (idemail, dni)-- llave primaria conbinada mismo tipo de datos
);



-- restricciones de tablas 
CREATE TABLE CARGO (
IDCARGO CHAR(7),
CARGO VARCHAR2(30) NOT NULL,
SUELDO NUMBER(2,3)-- ACEPTA NUMERO DE EL PRIMERO ES LA CANTIDAD DE NUMERO Q ACEPTA , Y EL SEGUNDO LA CANTIDAD DE DECIMALES EJ: 25.123
CONSTRAINT CH_SUELDO CHECK( SUELDO BETWEEN 200000 AND 600000 ),
CONSTRAINT PK_CARGO PRIMARY KEY (IDCARGO) 
);

ALTER TABLE TELEFONO -- CREA UN NUEVO CAMPO 
ADD MARCA NVARCHAR2(20);

ALTER TABLE TELEFONO
MODIFY (MARCA NOT NULL); -- EL CAMPO MARCA SE CAMBIA A NOT NULL

ALTER TABLE TELEFONO -- BORRAR UNA COLUMNA
DROP COLUMN MARCA;

ALTER TABLE TELEFONO
MODIFY MARCA NVARCHAR2(50) DEFAULT 'ENTER'; -- SI NO E  INGRESA NADA POR DEFECTO SE INSERTA ENTER

DESCRIBE TELEFONO;

CREATE TABLE CLIENTE(
DNI CHAR (10),
FECHA_REGISTRO DATE NULL,
CONSTRAINT PK_CLIENTE
PRIMARY KEY (DNI),
FOREIGN KEY (DNI) -- LLAVE FORANEA
 REFERENCES PERSONA (DOC) -- DOC TABLA PERSON 
);

ALTER TABLE PERSONA
ADD DIRECCION NCHAR(7);

describe persona;

ALTER TABLE PERSONA
ADD CONSTRAINT FK_DIRECCION FOREIGN KEY (DIRECCION)
REFERENCES DIRECCION (ID_DIRECCION);